[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[headers]]
  for = "/*"
  [headers.values]
    "Cache-Control" = "no-cache, no-store, must-revalidate"
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
